drop table if exists item CASCADE;
create table item(
                       item_no bigint generated by default as identity,
                       title varchar(255),
                       starting int,
                       deadline date,
                       content varchar(255),
                       writer varchar(255),
                       reg_date timestamp ,
                       primary key (item_no)
);
insert into item (title, starting, deadline, content, writer)
values ('시계 팔아요', '10000', '2021-07-07','시계는 와치', '시계장수');